---
title: "Construcción en Montevideo"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    # source_code: "https://github.com/daczarne/AppConstruccion"
runtime: shiny
---

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.0/css/all.css">

```{r global, include=FALSE}
construccion <- readr::read_rds(path = here::here("construccion.rds"))
library(magrittr, quietly = TRUE)
```

```{r variables_globales}
## Formato numérico
big_mark <- "."
decimal_mark <- ","
digits_permisos <- 0L

## Value Boxes
valuebox_color <- "#0570b0"
valuebox_icon_total <- "fas fa-hammer"
valuebox_icon_vivienda <- "fas fa-home"
valuebox_icon_comeindu <- "fas fa-industry"
valuebox_icon_otros <- "fas fa-building"
```

```{r reactive_functions}
## Devuelve la cantidad total de permisos en el año seleccionado por el usuario
total <- shiny::reactive({
   construccion %>%
      dplyr::transmute(
         year,
         variable = !!rlang::sym(input$variable)
      ) %>% 
      dplyr::group_by(
         year
      ) %>%
      dplyr::summarise(
         variable = base::sum(variable, na.rm = TRUE)
      ) %>%
      dplyr::filter(
         year == input$year
      ) %>%
      dplyr::pull()
})

## Devuelve la cantidad de permisos con destino vivienda en el año seleccionado por el usuario
vivienda <- shiny::reactive({
   construccion %>%
      dplyr::transmute(
         year,
         destino,
         variable = !!rlang::sym(input$variable)
      ) %>% 
      dplyr::group_by(
         year,
         destino
      ) %>%
      dplyr::summarise(
         variable = base::sum(variable, na.rm = TRUE)
      ) %>%
      dplyr::filter(
         year == input$year,
         destino == "Vivienda"
      ) %>%
      dplyr::pull(
         variable
      )
})

## Devuelve la cantidad de permisos con destino comercio en el año seleccionado por el usuario
comercio <- shiny::reactive({
   construccion %>%
      dplyr::transmute(
         year,
         destino,
         variable = !!rlang::sym(input$variable)
      ) %>% 
      dplyr::group_by(
         year,
         destino
      ) %>%
      dplyr::summarise(
         variable = base::sum(variable, na.rm = TRUE)
      ) %>%
      dplyr::filter(
         year == input$year,
         destino == "Comercio"
      ) %>%
      dplyr::pull(
         variable
      )
})

## Devuelve la cantidad de permisos con destino industria en el año seleccionado por el usuario
industria <- shiny::reactive({
   construccion %>%
      dplyr::transmute(
         year,
         destino,
         variable = !!rlang::sym(input$variable)
      ) %>% 
      dplyr::group_by(
         year,
         destino
      ) %>%
      dplyr::summarise(
         variable = base::sum(variable, na.rm = TRUE)
      ) %>%
      dplyr::filter(
         year == input$year,
         destino == "Industria"
      ) %>%
      dplyr::pull(
         variable
      )
})
```

Controles {.sidebar}
-----------------------------------------------------------------------

Cantidad de permisos de construcción emitidos por la IMM. Los datos se muestran con apertura por Tipo de permiso y destino del inmueble. El Tipo IPH equivale a Incorporación a Propiedad Horizontal.

```{r}
shiny::selectInput(
   inputId = "year",
   label = "Seleccione un año",
   selected = base::max(construccion$year),
   choices = base::sort(base::unique(construccion$year), decreasing = TRUE),
   multiple = FALSE
)

shiny::selectInput(
   inputId = "variable",
   label = "Seleccione una variable",
   selected = "permisos",
   choices = base::c(
      "Permisos" = "permisos",
      "Superficie (m2)" = "superficie"
   ),
   multiple = FALSE
)
```

Fuente: Instituto Nacional de Estadística.

```{r}
shiny::HTML(
   '<a href="https://danielczarnievicz.netlify.app/portfolio/construcci%C3%B3n-en-montevideo/"><i class="fas fa-arrow-circle-left"></i></a>&nbsp;
   <a href="https://github.com/daczarne/AppConstruccion"><i class="fab fa-github"></i></a>&nbsp;
   <a href="https://stackoverflow.com/users/5908830/daniel?tab=profile"><i class="fab fa-stack-overflow"></i></a>&nbsp;
   <a href="https://twitter.com/daczarne"><i class="fab fa-twitter"></i></a>&nbsp;
   <a href="https://www.linkedin.com/in/danielczarnievicz/"><i class="fab fa-linkedin"></i></a>&nbsp;
   <a href="https://danielczarnievicz.netlify.app/portfolio/"><i class="fas fa-home"></i></a>&nbsp;'
)
```


Row {data-width=100}
-----------------------------------------------------------------------

### Total

```{r}
flexdashboard::renderValueBox({
   flexdashboard::valueBox(
      value = formattable::comma(
         x = total(),
         digits = digits_permisos,
         big.mark = big_mark,
         decimal.mark = decimal_mark
      ),
      icon = valuebox_icon_total,
      color = valuebox_color
   )
})
```

### Vivienda

```{r}
flexdashboard::renderValueBox({
   flexdashboard::valueBox(
      value = formattable::comma(
         x = vivienda(),
         digits = digits_permisos,
         big.mark = big_mark,
         decimal.mark = decimal_mark
      ),
      icon = valuebox_icon_vivienda,
      color = valuebox_color
   )
})
```

### Comercio e Industria

```{r}
flexdashboard::renderValueBox({
   flexdashboard::valueBox(
      value = formattable::comma(
         x = comercio() + industria(),
         digits = digits_permisos,
         big.mark = big_mark,
         decimal.mark = decimal_mark
      ),
      icon = valuebox_icon_comeindu,
      color = valuebox_color
   )
})
```

### Otros/Varios

```{r}
flexdashboard::renderValueBox({
   flexdashboard::valueBox(
      value = formattable::comma(
         x = total() - vivienda() - comercio() - industria(),
         digits = digits_permisos,
         big.mark = big_mark,
         decimal.mark = decimal_mark
      ),
      icon = valuebox_icon_otros,
      color = valuebox_color
   )
})
```

Row {data-width=450}
-----------------------------------------------------------------------

### Permisos por tipo y destino

```{r}
plotly::renderPlotly({
   construccion %>% 
      dplyr::transmute(
         year,
         tipo,
         destino,
         variable = !!rlang::sym(input$variable)
      ) %>% 
      dplyr::filter(
         year == input$year
      ) %>% 
      dplyr::mutate(
         proporcion = variable / base::sum(variable, na.rm = TRUE) * 100
      ) %>% 
      plotly::plot_ly() %>% 
      plotly::add_trace(
         x = ~destino,
         y = ~tipo,
         type = "scatter",
         mode = "markers",
         marker = base::list(
            size = ~proporcion
         ),
         hovertemplate = ~base::paste0(
            "<b>Tipo</b>: %{y}",
            "<br>",
            "<b>Destino</b>: %{x}",
            "<br>",
            base::paste0("<b>", stringr::str_to_sentence(input$variable), "</b>: "),
            formattable::comma(
               x = variable,
               digits = digits_permisos,
               big.mark = big_mark,
               decimal.mark = decimal_mark
            )
         ),
         name = " "
      ) %>% 
      plotly::layout(
         xaxis = base::list(
            title = "<b>Destino</b>"
         ),
         yaxis = base::list(
            title = "<b>Tipo</b>"
         )
      ) %>% 
      plotly::config(
         locale = "es",
         displayModeBar = FALSE
      )
})
```
